[package]
name = "battery_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.28.0"
chrono = {version = "0.4", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
csv = "1.3"